# Site settings
title: Who am I?
description: A blog about development
baseurl: "/cards-jekyll-template" # the subpath of your site, e.g. /blog
url: "https://sunoko.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kazuki Chinone
user_description: Developer
email: ---@gmail.com
twitter_username: lorem_ipsum
github_username:  sunoko
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /About-me

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
